var hierarchy =
[
    [ "IBeginDragHandler", null, [
      [ "DraggableCommand", "class_draggable_command.html", null ]
    ] ],
    [ "IDragHandler", null, [
      [ "DraggableCommand", "class_draggable_command.html", null ]
    ] ],
    [ "IDropHandler", null, [
      [ "CommandSlot", "class_command_slot.html", null ],
      [ "CompilerGrid", "class_compiler_grid.html", null ]
    ] ],
    [ "IEndDragHandler", null, [
      [ "DraggableCommand", "class_draggable_command.html", null ]
    ] ],
    [ "IPointerClickHandler", null, [
      [ "DraggableCommand", "class_draggable_command.html", null ]
    ] ],
    [ "IPointerDownHandler", null, [
      [ "HoldingZoomer", "class_holding_zoomer.html", null ],
      [ "SkipStory", "class_skip_story.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "ButtonHover", "class_button_hover.html", null ],
      [ "ButtonSelection", "class_button_selection.html", null ],
      [ "EnviormentSwitch", "class_enviorment_switch.html", null ],
      [ "UICursorDescriptor", "class_u_i_cursor_descriptor.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "ButtonHover", "class_button_hover.html", null ],
      [ "ButtonSelection", "class_button_selection.html", null ],
      [ "EnviormentSwitch", "class_enviorment_switch.html", null ],
      [ "UICursorDescriptor", "class_u_i_cursor_descriptor.html", null ]
    ] ],
    [ "IPointerUpHandler", null, [
      [ "HoldingZoomer", "class_holding_zoomer.html", null ],
      [ "SkipStory", "class_skip_story.html", null ]
    ] ],
    [ "MonoBehaviour", null, [
      [ "Abyss", "class_abyss.html", null ],
      [ "AddCommandIfNone", "class_add_command_if_none.html", null ],
      [ "AnimatesMovementPanel", "class_animates_movement_panel.html", null ],
      [ "AnimatorDelay", "class_animator_delay.html", null ],
      [ "AppQuit", "class_app_quit.html", null ],
      [ "Astral", "class_astral.html", null ],
      [ "AutoLockDisabler", "class_auto_lock_disabler.html", null ],
      [ "BatController", "class_bat_controller.html", null ],
      [ "BlueCollider", "class_blue_collider.html", null ],
      [ "ButtonActivator", "class_button_activator.html", null ],
      [ "ButtonHover", "class_button_hover.html", null ],
      [ "ButtonSelection", "class_button_selection.html", null ],
      [ "CameraAnimator", "class_camera_animator.html", null ],
      [ "CameraBegining", "class_camera_begining.html", null ],
      [ "CameraController", "class_camera_controller.html", null ],
      [ "CameraHovering", "class_camera_hovering.html", null ],
      [ "CameraIdleMovement", "class_camera_idle_movement.html", null ],
      [ "CameraShake", "class_camera_shake.html", null ],
      [ "Casper", "class_casper.html", null ],
      [ "Checkpoint", "class_checkpoint.html", null ],
      [ "CinematicCamera", "class_cinematic_camera.html", null ],
      [ "CommandSlot", "class_command_slot.html", null ],
      [ "CompilerGrid", "class_compiler_grid.html", null ],
      [ "ContinueTimer", "class_continue_timer.html", null ],
      [ "CoreCompiler", "class_core_compiler.html", null ],
      [ "CountdownTimerImage", "class_countdown_timer_image.html", null ],
      [ "Crusher", "class_crusher.html", null ],
      [ "Cursor", "class_cursor.html", null ],
      [ "CursorSwitcherUI", "class_cursor_switcher_u_i.html", null ],
      [ "CutsceneCameraControl", "class_cutscene_camera_control.html", null ],
      [ "CutsceneManager", "class_cutscene_manager.html", null ],
      [ "DeathsCounterUI", "class_deaths_counter_u_i.html", null ],
      [ "DelayedAnimator", "class_delayed_animator.html", null ],
      [ "DeleteAllChildren", "class_delete_all_children.html", null ],
      [ "DeleteAllSlot", "class_delete_all_slot.html", null ],
      [ "DeleteSlot", "class_delete_slot.html", null ],
      [ "DescriptionOverHover", "class_description_over_hover.html", null ],
      [ "DisableAllEnviorments", "class_disable_all_enviorments.html", null ],
      [ "DisableChapterTitle", "class_disable_chapter_title.html", null ],
      [ "DisableStartAnimUI", "class_disable_start_anim_u_i.html", null ],
      [ "DisableTrashIcon", "class_disable_trash_icon.html", null ],
      [ "DiscoTile", "class_disco_tile.html", null ],
      [ "DisconnectChains", "class_disconnect_chains.html", null ],
      [ "DraggableCommand", "class_draggable_command.html", null ],
      [ "EnabelUI", "class_enabel_u_i.html", null ],
      [ "EndGateTrigger", "class_end_gate_trigger.html", null ],
      [ "EnviormentSwitch", "class_enviorment_switch.html", null ],
      [ "ErrorLabel", "class_error_label.html", null ],
      [ "Expressions", "class_expressions.html", null ],
      [ "EyeController", "class_eye_controller.html", null ],
      [ "EyeMovement", "class_eye_movement.html", null ],
      [ "FPSCounter", "class_f_p_s_counter.html", null ],
      [ "FenceController", "class_fence_controller.html", null ],
      [ "FidgetHord", "class_fidget_hord.html", null ],
      [ "GameManager", "class_game_manager.html", null ],
      [ "GateCameraControler", "class_gate_camera_controler.html", null ],
      [ "GateObstacle", "class_gate_obstacle.html", null ],
      [ "GridDrawer", "class_grid_drawer.html", null ],
      [ "HoldingZoomer", "class_holding_zoomer.html", null ],
      [ "InitiateGameCamera", "class_initiate_game_camera.html", null ],
      [ "Inserter", "class_inserter.html", null ],
      [ "InteractionButton", "class_interaction_button.html", null ],
      [ "Item", "class_item.html", null ],
      [ "ItemDescription", "class_item_description.html", null ],
      [ "JellyText", "class_jelly_text.html", null ],
      [ "KeyManager", "class_key_manager.html", null ],
      [ "KeyboardManager", "class_keyboard_manager.html", null ],
      [ "LaserControler", "class_laser_controler.html", null ],
      [ "LaserManager", "class_laser_manager.html", null ],
      [ "LaserReceiver", "class_laser_receiver.html", null ],
      [ "LevelLocker", "class_level_locker.html", null ],
      [ "Lever", "class_lever.html", null ],
      [ "LineConnector", "class_line_connector.html", null ],
      [ "LoadInGame", "class_load_in_game.html", null ],
      [ "LoadingAssets", "class_loading_assets.html", null ],
      [ "MilithHordController", "class_milith_hord_controller.html", null ],
      [ "MistyController", "class_misty_controller.html", null ],
      [ "MistyMenu", "class_misty_menu.html", null ],
      [ "MusicFader", "class_music_fader.html", null ],
      [ "MusicToggle", "class_music_toggle.html", null ],
      [ "Obstacle", "class_obstacle.html", null ],
      [ "ObstacleSensor", "class_obstacle_sensor.html", null ],
      [ "OpenMenu", "class_open_menu.html", null ],
      [ "OpenURL", "class_open_u_r_l.html", null ],
      [ "PauseGlobal", "class_pause_global.html", null ],
      [ "PlayerController", "class_player_controller.html", null ],
      [ "PlayerEye", "class_player_eye.html", null ],
      [ "PlayerStep", "class_player_step.html", null ],
      [ "PressContinue", "class_press_continue.html", null ],
      [ "PressEsc", "class_press_esc.html", null ],
      [ "PressEscPauseMenu", "class_press_esc_pause_menu.html", null ],
      [ "Prism", "class_prism.html", null ],
      [ "PrismSlide", "class_prism_slide.html", null ],
      [ "PushButton", "class_push_button.html", null ],
      [ "PushManager", "class_push_manager.html", null ],
      [ "QuestionMarkDisable", "class_question_mark_disable.html", null ],
      [ "RainbowUI", "class_rainbow_u_i.html", null ],
      [ "Reflection", "class_reflection.html", null ],
      [ "ReflectionCamera", "class_reflection_camera.html", null ],
      [ "RemoveSaves", "class_remove_saves.html", null ],
      [ "ResetCursorImage", "class_reset_cursor_image.html", null ],
      [ "ResetSelectors", "class_reset_selectors.html", null ],
      [ "ResolutionSlider", "class_resolution_slider.html", null ],
      [ "RespawnParticle", "class_respawn_particle.html", null ],
      [ "RestartLevel", "class_restart_level.html", null ],
      [ "Rotator", "class_rotator.html", null ],
      [ "ScoreItemUI", "class_score_item_u_i.html", null ],
      [ "ScreenManager", "class_screen_manager.html", null ],
      [ "SelfDisable", "class_self_disable.html", null ],
      [ "SelfEnable", "class_self_enable.html", null ],
      [ "SkeletonObstacle", "class_skeleton_obstacle.html", null ],
      [ "SkipStory", "class_skip_story.html", null ],
      [ "SlotCreater", "class_slot_creater.html", null ],
      [ "SoundSlider", "class_sound_slider.html", null ],
      [ "SpawnScoreItemUI", "class_spawn_score_item_u_i.html", null ],
      [ "Spike", "class_spike.html", null ],
      [ "SplashScreenSkip", "class_splash_screen_skip.html", null ],
      [ "Star", "class_star.html", null ],
      [ "StarRatingPanel", "class_star_rating_panel.html", null ],
      [ "StopTimer", "class_stop_timer.html", null ],
      [ "StoryCamController", "class_story_cam_controller.html", null ],
      [ "SummonAnimationDisable", "class_summon_animation_disable.html", null ],
      [ "Swell", "class_swell.html", null ],
      [ "SwingBlade", "class_swing_blade.html", null ],
      [ "SystemManager", "class_system_manager.html", null ],
      [ "TextVibration", "class_text_vibration.html", null ],
      [ "Timer", "class_timer.html", null ],
      [ "TraceController", "class_trace_controller.html", null ],
      [ "TrashingDirection", "class_trashing_direction.html", null ],
      [ "TriggerMisty", "class_trigger_misty.html", null ],
      [ "TutorialEnabler", "class_tutorial_enabler.html", null ],
      [ "TutorialSkipper", "class_tutorial_skipper.html", null ],
      [ "TypeshakerEffect", "class_typeshaker_effect.html", null ],
      [ "UIButtonSound", "class_u_i_button_sound.html", null ],
      [ "UICursorDescriptor", "class_u_i_cursor_descriptor.html", null ],
      [ "UIDescriptor", "class_u_i_descriptor.html", null ],
      [ "UIHover", "class_u_i_hover.html", null ],
      [ "UIPlatformManager", "class_u_i_platform_manager.html", null ],
      [ "UIReselector", "class_u_i_reselector.html", null ],
      [ "VersionDisplay", "class_version_display.html", null ],
      [ "WinZoom", "class_win_zoom.html", null ]
    ] ]
];